### ISSUE TITLE
Version cloudsmith-cli==1.1.0 is failing when uploading npm packages

### ISSUE THREAD

**Issue by RokPapez** [cloudsmith-io/cloudsmith-cli#147]
Hi,

we noticed that using version cloudsmith-cli==1.1.0 fail with the following error when uploading npm packages:

`cloudsmith push npm $org/$repo $some_package.tgz`

`Checking npm package upload parameters ... Traceback (most recent call last):
  File "/usr/local/bin/cloudsmith", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/decorators.py", line 100, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/decorators.py", line 139, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/decorators.py", line 61, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/decorators.py", line 191, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/decorators.py", line 309, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/commands/push.py", line 517, in push_handler
    upload_files_and_create_package(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/commands/push.py", line 341, in upload_files_and_create_package
    validate_create_package(
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/cli/commands/push.py", line 148, in validate_create_package
    api_validate_create_package(
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/core/api/packages.py", line 47, in validate_create_package
    client = get_packages_api()
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/core/api/packages.py", line 16, in get_packages_api
    return get_api_client(cloudsmith_api.PackagesApi)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/core/api/init.py", line 70, in get_api_client
    client.api_client.rest_client = RestClient(
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/core/rest.py", line 168, in __init__
    self.session = create_requests_session(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/core/rest.py", line 106, in create_requests_session
    retry = RetryWithCallback(
  File "/usr/local/lib/python3.8/dist-packages/cloudsmith_cli/core/rest.py", line 25, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'allowed_methods`

`python3 --version
Python 3.8.10`

`lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal`

Downgrading back to version cloudsmith-cli==1.0.0 works as expected.

Kind regards.

**Comment by lskillen** [comment]
Hey @RokPapez - The team released some features that require a newer version of the API bindings. So you have the same issue if you upgrade the `cloudsmith-api` to the latest as well? 🤔

**Comment by slonopotamus** [comment]
I'm getting the same error trying to use `cloudsmith push`: https://github.com/octobuild/octobuild/actions/runs/6168804704/job/16741910576

**Comment by RokPapez** [comment]
Hi @lskillen ,

I didn't test  this yet. We are doing the installation during running pipeline, which means installing latest package version available (pip install cloudsmith-cli). I just bumped the version of the image we are using for building npm packages on version which is based on ubuntu 22.04. There it works nornally. Per my understanding it should be connected with the python version. 

`python --version
Python 3.10.12`

Just tested to reproduce this in docker, so this are the libs which are installed by default when installig it:

`pip freeze
]certifi==2019.11.28
chardet==3.0.4
click==8.1.7
click-configfile==0.2.3
click-didyoumean==0.3.0
click-spinner==0.1.10
cloudsmith-api==2.0.7
cloudsmith-cli==1.1.0
configparser==6.0.0
dbus-python==1.2.16
distro-info===0.23ubuntu1
idna==2.8
PyGObject==3.36.0
python-apt==2.0.0+ubuntu0.20.4.7
python-dateutil==2.8.2
requests==2.22.0
requests-toolbelt==1.0.0
requests-unixsocket==0.2.0
semver==3.0.1
six==1.14.0
unattended-upgrades==0.1
urllib3==1.25.8`

If this somehow helps.

**Comment by chrisimcevoy** [comment]
Related to #146 

Upgrading urllib3 to >= 1.26.0 should make this work for 1.1.0, but I understand that isn't possible in certain environments e.g. Ubuntu 20.04.

Team is working on a patch - more to follow.

**Comment by chrisimcevoy** [comment]
Please take the latest release (v1.1.1) which should resolve this issue for you.

**Comment by slonopotamus** [comment]
Confirming 1.1.1 solved my issue. Thanks for quick reaction.
