### ISSUE TITLE
Error uploading to private repository via cli

### ISSUE THREAD

**Issue by mcclory** [cloudsmith-io/cloudsmith-cli#2]
## Steps to reproduce

* set up new `virtualenv` and install dependencies, including cloudsmith-cli 
* set `CLOUDSMITH_API_KEY` env variable to appropriate key
* build python (3.5.2) package using `setuptools`/`distutils` (successful)
* run process to upload python package to cloudsmith via cli tools
* process errors as described below

## Expected behavior

Upload occurs, placing package in proper repository per input values at the command line level. Outcome is identical to the process that would occur if uploaded by web UI (I have confirmed this works w/ the same package attempted via cli).

## STDERR Output

```bash 
$ python setup.py bdist_wheel
$ package_filename=$(ls dist)
$ cloudsmith push python private-org/python dist/$package_filename

Checking python package upload parameters ... OK
Checking private-org.models.common-0.1.0-py2.py3-none-any.whl file upload parameters ... OK
Requesting file upload for private-org.models.common-0.1.0-py2.py3-none-any.whl ... OK
Uploading private-org.models.common-0.1.0-py2.py3-none-any.whl:  [------------------------------------]    0%
Traceback (most recent call last):
  File "/home/pmdev/.virtualenvs/models/bin/cloudsmith", line 11, in <module>
    sys.exit(main())
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/cli/decorators.py", line 40, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/cli/decorators.py", line 65, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/cli/decorators.py", line 81, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/cli/decorators.py", line 119, in wrapper
    return ctx.invoke(f, *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/cli/commands/push.py", line 382, in push_handler
    upload_files_and_create_package(ctx, *args, **kwargs)
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/cli/commands/push.py", line 245, in upload_files_and_create_package
    skip_errors=skip_errors, md5_checksum=md5_checksums[k]
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/cli/commands/push.py", line 94, in upload_file
    callback=progress_callback
  File "/home/pmdev/.virtualenvs/models/lib/python3.5/site-packages/cloudsmith_cli/core/api/files.py", line 62, in upload_file
    upload_fields.append(
AttributeError: 'dict_items' object has no attribute 'append'
```

## Environment Details

* python version: `Python 3.5.2`
* OS: Elementary OS 0.4.1
* `uname -a`: `Linux asus13 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

### packages installed in virtualenv

```bash
certifi==2017.11.5
chardet==3.0.4
click==6.7
click-configfile==0.2.3
click-didyoumean==0.0.3
click-spinner==0.1.7
cloudsmith-api==0.21.3
cloudsmith-cli==0.3.1
colorama==0.3.9
configparser==3.5.0
idna==2.6
mongoengine==0.15.0
nose==1.3.7
nose-mongoengine==0.2.2
pep8==1.7.1
pycodestyle==2.3.1
pymongo==3.6.0
python-dateutil==2.6.1
requests==2.18.4
requests-toolbelt==0.8.0
semver==2.7.9
simplejson==3.13.2
six==1.11.0
urllib3==1.22
```

## Notes 

This looks like just a bad assumption related to the `upload_fields` object [here](https://github.com/cloudsmith-io/cloudsmith-cli/blob/master/cloudsmith_cli/core/api/files.py#L62), but it looks like this is being passed through from the upstream API, so I'm hesitant to fork and fix as I assume this was a `list` at one point where now a `dict` is present.

**Comment by lskillen** [comment]
@mcclory Fantastic report, thank you!

It looks like this is a py2 vs py3 issue - It was developed primarily within py2 and we haven't implemented the test coverage yet to fully exercise it via py3 (but example integrations repository will be released before the new year, so at least we'll have an end-to-end test in py2 and py3!) The `items()` call returns a `list` within py2 but a `dict_items` within py3, so a quick fix here is to coerce it into `list`. A PR is more than welcome if you'd like to get your name stamped in the book! :-)

**Comment by mcclory** [comment]
I'll check it out then :)  should be coming up shortly... and get back to not working.. plz!

**Comment by lskillen** [comment]
Fixed - thanks!
